server:
  port: 8080
  compression:
    enabled: true

web:
  domain: http://localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ***
    password: ***
    url: jdbc:mysql://***:3306/blog?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource

  # 上传服务
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 邮箱
  mail:
    host: smtp.aliyun.com
    username: ***
    password: "***"
    port: 465
    properties.smtp.auth: true
    properties.smtp.timeout: 2500
    properties.mail.smtp.ssl.enable: true

# 上传路径
upload:
  dir : /home/qdl/Desktop/gallery/

# 图片网络访问路径
img:
  imgURL: http://localhost:8080/images/

logging:
  level:
    root: info
    com.lin: debug

# 验证码消息
msg:
  send: 为完成注册认证, 请输入验证码，您的验证码为
  sendBack:  正在重置密码，为完成重置验证,请输入验证码，您的验证码为

